### PR TITLE
User-selectable menu inverse scrolling for Enc2/Enc3 encoders

### PR DESCRIPTION
**Pull request by frazierjason**
Add display menu option to invert the menu navigation for Enc2/Enc3.  This is intended to use on radios with encoders mounted on the right hand side (such as mcHF v0.7) to allow a more intuitive UI experience.  When turned on, turning Enc2 clockwise will advance the selected menu item vertically up toward the top of the screen, and turning Enc3 clockwise while focused on an opened menu group will hide the group.

No other encoder operations are affected; turning the dials clockwise will increment/advance all other selected values as usual.

### CODE REVIEW

**Comment by frazierjason** [comment]
Forgot to mention, tested and works great for me. The navigation changes worked as expected for the last two weeks, and I tested the save option lay night on v0.6 and v0.7 units.

**Comment by sp9bsl** [comment]
Hi,
it works, but wouldn't it be better to have reverse option on all encoders saparately  instead of this?

**Comment by db4ple** [comment]
Hi,
we should not mix things here. The pull request does not makes it possible change the encoder direction in general, it changes the direction the menu code interprets the encoder direction. That means as the pull request message says (Thanks Jason, this one was very good)., encoder direction does not change in general. And cannot be solved by implementing a change of encoder directions per encoder (as this would not differentiate between Menu vs. not in Menu operation).

BTW, I am not saying that I think that the changed direction makes sense for me personally since I never used a 0.7. I would rather think that the normal direction would be the "right one" for me. But I would have to try this on the real thing to be sure. 

I would also suggest not to put this in the Display menu but in the Configration menu (which is intended for mostly one-time configuration items) menu, but that is a minor thing.

**Comment by frazierjason** [comment]
Hi Danilo,

Thanks for sharing this info on the menu group intents.  I am not opposed to someone moving the menu option from Display to Configuration menu group, if there are strong organizational feelings about where to put it.  But this new option addresses a cosmetic display-related visual issue, so I figured people would look in there since it feels like the screen is going the wrong way when it's not set up right.  If you are correct that some people will feel the non-inverted experience is the "right one", then this becomes not a one-time configuration, but something that might get reconfigured for personal taste every time the radio changes hands.

If there are no other objections, then we can close issue #1319.

73 de Jason W7DM

**Pull request merged**
