### PR TITLE
Implementing BPSK modulation #1002

### PR DESCRIPTION
**Pull request by phaethon**
Demodulation is still in works, but somebody if interested can test out transmission meanwhile.

### CODE REVIEW

**Comment by df8oe** [comment]
This does not build (see travis-ci output). Please take a look at that again.

**Comment by phaethon** [comment]
On eclipse it did build. Added to files.mak and f7-files.mak, and now is ok with Travis, too. 
btw, it is not nice that the file needs to be added manually to both files. Would be better to have files.mak for common files for all platforms, and then f4-files.mak and f7-files.mak for platform specific.

**Comment by db4ple** [comment]
Yes, you are right re two files. But on the other hand, it is not too much work. Wait until we have the H7, then you can add that to three files ;-)

I think we should fix that. This would even make the naming scheme a little more logical...

**Comment by phaethon** [comment]
I hardly imagine how we will assure reasonable testing across multiple hardware platforms. I naturally test only on what I have (which is original mchf with f4).

**Comment by db4ple** [comment]
Well, that is naturally going to be a challenge.

**Comment by db4ple** [comment]
Hi Eriks,
I would factor the F4 specific files out (into f4-files.mak) and leave the common files in files.mak  in one of my next pull requests. Or do you want to do this for the makefile builds?

**Comment by phaethon** [comment]
Please, do it.

**Pull request merged**
