### PR TITLE
VKeypad. Change colour of pressed button text, some other minor changes.

### PR DESCRIPTION
**Pull request by sp9bsl**

### CODE REVIEW

**Comment by DG9BFC** [comment]
aehem ... why not ALL buttons are changed in colour?!?
or is it just for testing things out?!?

**Comment by sp9bsl** [comment]
Hi Sigi,
works as expected (at least for me).  I changed the green text on pressed button to white to make it better visible. Did you expected some other changes?

**Comment by DG9BFC** [comment]
check dsp buttons ... why is lower left in yellow??

**Comment by sp9bsl** [comment]
https://github.com/df8oe/UHSDR/wiki/Operating-Manual#dsp-virtual-keypad
Yellow means WARNING, it is intented.

**Comment by DG9BFC** [comment]
ah ok ... that is if you have spi display (that slows dsp down) ... with parallel display it works fine and so no warning needed .... what if you only change that colour if a spi display is used?!? ... with a parallel display the dsp works with nr + notch with no problems ... and in the info screen you can see what display is used ... so warning colour could be made active only if a spi display is  used (ok ok it is just cosmetics)

**Comment by sp9bsl** [comment]
Yes, you're right. Will add some code to check this.

**Pull request merged**
