### PR TITLE
Lcd experimental

### PR DESCRIPTION
**Pull request by sp9bsl**
I changed some LCD port definitions for OVI40 board to "unstealth it". Andreas you need to connect LCD CS port to D11 port of lcd socket on your UI board.

### CODE REVIEW

**Comment by sp9bsl** [comment]
I see conflicts again, i rebased few minutes ago. Just before i changed file i commited...

**Comment by db4ple** [comment]
Hi

We messed something up in this branch, hence   it seems we get conflicts here. As I said, not your fault. I will discuss with Andreas how to fix that.
73
Danilo

**Comment by sp9bsl** [comment]
Danilo, may i modify the code in my computer when you do things with this pull request?

**Comment by db4ple** [comment]
Yes, absolutely no problem.

**Pull request merged**
