### PR TITLE
Removed including HAL STM32 from config file. Reorganise configuring the boards.

### PR DESCRIPTION
**Pull request by m-chichikalov**
This is a just small step to broke dependencies on STM32 HAL.

- Created folder for board specific config files.
- Reversed dependencies, explicitly should be mention for which RF and
UI boards compiled binary -> edit travis.yml
- Removed STM32 HAL from uhsdr_board_config.h
- Uhsdr_board_config.h should be included by modules to get settings.
- probably more settings should be moved from uhsdr_board.h to
uhsdr_board_config.h

20 files, but changes are not spreaded all other th whole files, so I do not think that someone will have a problem with rebasing.

### CODE REVIEW

**Comment by df8oe** [comment]
Hi Maks,

nice start. Can you please add neccessary changes to Eclipse configuration files, too? Using Eclipse with import the folder should work out of the box, too...

And (I am not sure you are using it) can you take a look at Embitz configuration? If not: not a problem - leave it as-it-is. But if you do have installed Embitz, too it would be very nice if you take a look there, too. Functionality of Embitz ist lost since a longer time (because no of the developers uses it).

**Comment by db4ple** [comment]
Hi Max, Andreas,
I think fixing the already broken EmBitz config is asking too much (but is very welcome). To make sure that Eclipse and Makefile, which are both actively used, are in line on this kind of changes, is relevant, though.
@m-chichikalov: You don't have to do Eclipse if you change the Makefile but someone should. Currently I maintain the Eclipse builds, so you may trigger me or do it yourself. Thank you!

BTW, nice commit.

**Comment by df8oe** [comment]
@m-chichikalov : Maybe I was unclearly: of course IT IS NOT mandatory to fix Embitz! But sometimes such things are very easy for someone else but not for everyone. So it is JUST A QUESTION without any obligation!

**Comment by m-chichikalov** [comment]
Currently I maintain the Eclipse builds, so you may trigger me or do it yourself. Thank you!
> 
> BTW, nice commit.

Thank you,
I added eclipse project files to exclude and do not use it to build as has a problem with building from eclipse (something wrong with PATH, do not want to figure out, maube later) as a result cannot test, so Danilo, could you mind to align Eclipse settings? (And it's really strange because I easily working from Eclipse with others projects, but cannot build UHSDR, even with adding Linux Tools)

On my side I will take a look to EmBitz, anyway wanted to try it on.

**Comment by m-chichikalov** [comment]
Installed EmBitz, No, sorry do not have time figure out it. Maybe later...
Danilo, Hi, would you update Eclipse settings or I'm on it? Just let me know that we both do not do that.

**Comment by db4ple** [comment]
I can do this, just need Andreas to accept PR and will then update Eclipse config.

**Comment by m-chichikalov** [comment]
Ok, thanks.

**Comment by df8oe** [comment]
..let's go!

**Comment by m-chichikalov** [comment]
> ..let's go!

Yep, hope I broke only dependencies ;)

**Comment by sp9bsl** [comment]
I have some conflicts around uhsdr_board.h, hope resolve it soon. My ddc-experimental branch touches the same files. Working...

**Comment by sp9bsl** [comment]
hmm, can you point me where should be defined now one of: UI_BRD_MCHF UI_BRD_OVI40. I have problem with build.

**Comment by db4ple** [comment]
I also don't like the fact that there is no "default" configuration (`make all` simply fails).

**Comment by db4ple** [comment]
One solution would be to issue a proper warning via preprocessor to tell the user what to do. That would work in Eclipse as well.

**Comment by sp9bsl** [comment]
why Travis did not marked this as failed??

**Comment by m-chichikalov** [comment]
> I also don't like the fact that there is no "default" configuration (`make all` simply fails).

But it tels you why. Maybe make all should compile for F4 RF_MCHF and UI_MCHF as a default config... However I profer to have error and know I need specify

**Comment by db4ple** [comment]
Because all travis makes have the necessary defines as CONFIG_FLAGS..

**Comment by m-chichikalov** [comment]
> why Travis did not marked this as failed??

Because I corrected travis config file, wait, everything going to be fine after Danilo correct config for Eclipse

**Comment by sp9bsl** [comment]
Ok, I will wait for update, no problem.

**Comment by db4ple** [comment]
Max, yes, it tells but it scrolls so fast that I did not bother to look at the begin of the messages. We should improve this.

**Comment by m-chichikalov** [comment]
I implemented it like error, should stop instantly, only one way that you pass the flag to make do not stop on errors?

**Comment by db4ple** [comment]
Hm. Not instantly. I had make -j4 running, that did make it easier.

A default setting in the makefile would really solve that issue. 
Or an check there.

```
  [CC] basesw/mcHF/Src/i2s.o
  [CC] basesw/mcHF/Src/main.o
In file included from ./hardware/uhsdr_board.h:17:0,
                 from ./src/uhsdr_main.h:19,
                 from basesw/mcHF/Src/main.c:86:
./hardware/uhsdr_board_config.h:23:6: error: #error One ui board has to be selected: UI_BRD_MCHF, UI_BRD_OVI40
     #error One ui board has to be selected: UI_BRD_MCHF, UI_BRD_OVI40
      ^~~~~
./hardware/uhsdr_board_config.h:33:6: error: #error One rf board has to be selected: RF_BRD_MCHF, RF_BRD_OVI40
     #error One rf board has to be selected: RF_BRD_MCHF, RF_BRD_OVI40
      ^~~~~
In file included from ./hardware/uhsdr_board.h:18:0,
                 from ./src/uhsdr_main.h:19,
                 from basesw/mcHF/Src/main.c:86:
./hardware/uhsdr_board.h: In function 'Board_GreenLed':
./hardware/uhsdr_board.h:875:22: error: 'GREEN_LED_PIO' undeclared (first use in this function)
         GPIO_SetBits(GREEN_LED_PIO, GREEN_LED);
                      ^
./hardware/uhsdr_mcu.h:56:40: note: in definition of macro 'GPIO_SetBits'
     #define GPIO_SetBits(PORT,PINS) { (PORT)->BSRR = (PINS); }
                                        ^~~~
./hardware/uhsdr_board.h:875:22: note: each undeclared identifier is reported only once for each function it appears in
         GPIO_SetBits(GREEN_LED_PIO, GREEN_LED);
                      ^
./hardware/uhsdr_mcu.h:56:40: note: in definition of macro 'GPIO_SetBits'
     #define GPIO_SetBits(PORT,PINS) { (PORT)->BSRR = (PINS); }
                                        ^~~~
./hardware/uhsdr_board.h:875:37: error: 'GREEN_LED' undeclared (first use in this function); did you mean 'GREEN_LED_PIO'?
         GPIO_SetBits(GREEN_LED_PIO, GREEN_LED);
                                     ^
./hardware/uhsdr_mcu.h:56:55: note: in definition of macro 'GPIO_SetBits'
     #define GPIO_SetBits(PORT,PINS) { (PORT)->BSRR = (PINS); }
                                                       ^~~~
./hardware/uhsdr_board.h: In function 'Board_RedLed':
./hardware/uhsdr_board.h:891:22: error: 'RED_LED_PIO' undeclared (first use in this function)
         GPIO_SetBits(RED_LED_PIO, RED_LED);
                      ^
./hardware/uhsdr_mcu.h:56:40: note: in definition of macro 'GPIO_SetBits'
     #define GPIO_SetBits(PORT,PINS) { (PORT)->BSRR = (PINS); }
                                        ^~~~
./hardware/uhsdr_board.h:891:35: error: 'RED_LED' undeclared (first use in this function); did you mean 'READ_REG'?
         GPIO_SetBits(RED_LED_PIO, RED_LED);
                                   ^
./hardware/uhsdr_mcu.h:56:55: note: in definition of macro 'GPIO_SetBits'
     #define GPIO_SetBits(PORT,PINS) { (PORT)->BSRR = (PINS); }
                                                       ^~~~
./hardware/uhsdr_board.h: In function 'Board_EnableTXSignalPath':
./hardware/uhsdr_board.h:928:22: error: 'PTT_CNTR_PIO' undeclared (first use in this function); did you mean 'PWR_CSR_PVDO'?
         GPIO_SetBits(PTT_CNTR_PIO,PTT_CNTR);     // TX on and switch CODEC audio paths
                      ^
./hardware/uhsdr_mcu.h:56:40: note: in definition of macro 'GPIO_SetBits'
     #define GPIO_SetBits(PORT,PINS) { (PORT)->BSRR = (PINS); }
                                        ^~~~
./hardware/uhsdr_board.h:928:35: error: 'PTT_CNTR' undeclared (first use in this function); did you mean 'PTT_CNTR_PIO'?
         GPIO_SetBits(PTT_CNTR_PIO,PTT_CNTR);     // TX on and switch CODEC audio paths
                                   ^
./hardware/uhsdr_mcu.h:56:55: note: in definition of macro 'GPIO_SetBits'
     #define GPIO_SetBits(PORT,PINS) { (PORT)->BSRR = (PINS); }
                                                       ^~~~
In file included from ./src/uhsdr_main.h:19:0,
                 from basesw/mcHF/Src/main.c:86:
./hardware/uhsdr_board.h: In function 'Board_PttDahLinePressed':
./hardware/uhsdr_board.h:976:31: error: 'PADDLE_DAH_PIO' undeclared (first use in this function); did you mean 'PADDLE_DAH_Pin'?
     return  !HAL_GPIO_ReadPin(PADDLE_DAH_PIO,PADDLE_DAH);
                               ^~~~~~~~~~~~~~
                               PADDLE_DAH_Pin
./hardware/uhsdr_board.h:976:46: error: 'PADDLE_DAH' undeclared (first use in this function); did you mean 'PADDLE_DAH_PIO'?
     return  !HAL_GPIO_ReadPin(PADDLE_DAH_PIO,PADDLE_DAH);
                                              ^~~~~~~~~~
                                              PADDLE_DAH_PIO
./hardware/uhsdr_board.h: In function 'Board_DitLinePressed':
./hardware/uhsdr_board.h:983:31: error: 'PADDLE_DIT_PIO' undeclared (first use in this function); did you mean 'PADDLE_DIT_Pin'?
     return  !HAL_GPIO_ReadPin(PADDLE_DIT_PIO,PADDLE_DIT);
                               ^~~~~~~~~~~~~~
                               PADDLE_DIT_Pin
./hardware/uhsdr_board.h:983:46: error: 'PADDLE_DIT' undeclared (first use in this function); did you mean 'PADDLE_DIT_PIO'?
     return  !HAL_GPIO_ReadPin(PADDLE_DIT_PIO,PADDLE_DIT);
                                              ^~~~~~~~~~
                                              PADDLE_DIT_PIO
Makefile:257: recipe for target 'basesw/mcHF/Src/main.o' failed
make: *** [basesw/mcHF/Src/main.o] Error 1
```

**Comment by m-chichikalov** [comment]
Ok, maybe echoing from Makefile?

**Comment by db4ple** [comment]
Successfully compiled the 3 firmware binaries via Eclipse (not tested) and the 3 bootloaders.
Will do the PR now.

**Comment by df8oe** [comment]
I do have some questions for adapting my bash building script file.

It is not a problem to pass new parameter CONFIGFLAGS="-DUI_BRD_MCHF -DRF_BRD_MCHF". But if I build OVI40 it runs at mcHF AND OVI40 board without selecting anything - and this is a MUST at the actual state.

So in my view at the actual state there are only disadvantages by selecting UI and/or RF board for make buils. If I build for F4 it is ALWAYS for mcHF UI and mcHF RF and if I build for F7 or H7 it is ALWAYS for OVI40 UI AND (mcHF RF AND OVI40 RF). So what to do? The selection of UI boards is already done by MCU type and a selection of RF boards is distructing because there are autodetecting of RF boards in firmware. It would be a great loss if firmware for F7 and H7 does not work on mcHF RF and OVI40 RF out of the box...

**Comment by db4ple** [comment]
RF_BRD_MCHF or RF_BRF_OVI40: At the moment this is a completely irrelevant choice, as there is no real information attached to these defines. So no matter what we select (For Eclipse I selected RF_BRD_MCHF for all configurations, BTW), you'll get the same thing. But as @df8oe pointed out, A single UI BOARD potentialy  intended to support multiple RF boards (but not necessarily all of them). Just like the graphics controller. At build time we want to select some of the rf boards and then some detection will detect the actual configuration.  We do this implicitly already based on the oscillator we identify to a certain extent.

So as a first measure we either remove the unused defines for now OR at least change it to a non-empty set constraint for rf boards (at least one board has to be selected). I am good with both. However, we should try to avoid to much anticipation of future improvements by introducing (mandatory) settings with no real effect in the code.

**Comment by df8oe** [comment]
My vote is to remove the unused settings. In my mind there is nothing in near future which can be improved by this I only see things that can be prevented by this and it produces confusion because of firmware binary can support more than one board.

**Comment by sp9bsl** [comment]
Hi, 
so far I understood that since now, when introducing new RF board I must change the Travis AND eclipse right? I'm asking because I'm in this moment. Anyway I will wait untill the dust settle, and then hopefuly rebase.

**Comment by df8oe** [comment]
@sp9bsl : not in every case. If you have implemented new hardware by compiletime #defines YES. I do not know how much code is needed and if an "autodetection" is possible. If autodetection can be realized of course no change to travis has to be done.

**Comment by sp9bsl** [comment]
ok, thank you Andreas. So far I use autodetection, but wondered about new RF board definition because some of gpios we use today will not be needed or change its meaning. Ok, when reach the moment will open a discussion in Sulingen forum for this.

**Comment by m-chichikalov** [comment]
Hi Guys, you called it Universal, think about someone who come tomorrow and will adopte UHSDR for his HARDWARE, Hi can use MCHF_UI_CONFIG with different MCU, I did it not because I think it's good, you devided code on the UI_MCHF and RF_MCHF, I would vote that should be mention explicitly during compiling atleast for **which MCU** and **what kindof Board**, because before I put changes the code decieded which board to build only on the type of MCU, I think it's not right.... But, yes I agree for this time to pass UI and RF boards type is redundancy...

I can add default value to put it back as before if it's F4 and nothing mention -> MCHF_boards
if F7 and nothing mention-> OVI40;  h7->ovi40h7. so, we do not devided settings on the RF and UI, and dedicated one file for each "TRX" does not matte what kind of rf boards. And inside this file defines which RF board. This is OK?

**Comment by df8oe** [comment]
Hi Maks,
"universal" does not mean every hardware is supported. In our project description is mentioned "...supported hardware..." and we (the developers team) decide what hardware is supported by the main project and what not. If we do not regulate here there can come up a flood of "partially supported", "uncompletely supported", "never  available" e.g. hardware. And many things will be detected on runtime. Splitting firmware binaries into many different binaries make it much more difficult to maintain it and can lead to confusion for the users. At the given state this feature should be deactivated completely (there is nothing that must be changed in build process) or removed... Other opinions (Slawek, Danilo)?

**Comment by m-chichikalov** [comment]
> Hi Maks,
> "universal" does not mean every hardware is supported. In our project description is mentioned "...supported hardware..." and we (the developers team) decide what hardware is supported by the main project and what not. If we do not regulate here there can come up a flood of "partially supported", "uncompletely supported", "never available" e.g. hardware. And many things will be detected on runtime. Splitting firmware binaries into many different binaries make it much more difficult to maintain it and can lead to confusion for the users. 


I agree, but as I'm trying to go close to porting another hardware, how should I manage it? Or I should go to my local repo and do not bother you, just tell me...

**Comment by sp9bsl** [comment]
Andreas, agree. I prefer the way we first discuss and then go (like today happened from Danilo). Just to be prepared for the final effect.

**Comment by sp9bsl** [comment]
Maksim, all we do is for our common happiness, not to satisfy one developer. Please think about UHSDR as project for thousands of users using it already, and for those who develop sometimes new things for it. What project do you want to be connected to UHSDR? Malamute? Please think about testing, almost every change must be verified with all hardware before go...

**Comment by df8oe** [comment]
Hi Maks,
implementing completely new hardware like the already finshed porting to F7 and H7, the integration of 480x320 LCD was made on cloned repos of the origin. When everything is finished and tested it can be added by pull request. "active devel" does not mean it is an instable and experimental branch! Experiments should be done in seperate branches and for better overview I do not implement all these branches here. They can stay at the GitHubs of the persons who are working on it. Very urgend and important things of course can be added here in new branch.

**Comment by m-chichikalov** [comment]
I thought it's good to have as much as passible supported hardware, as much as passible hardware independent code which will bring another SW developers and new users which ready to test every time, which bring uncreadable ideas and so on... 

What if I want compile UHSDR fw for F7 but the MCHF pins and peripheral settings? Ok, you are not supported this configuration, I think no one asking to support but if it's easily possible, why not. And might be mention that officially supported only 4 configurations F4,F4-small, OVI40 & OVI-H7.  Any others are on own risk.

Ok... I got your point of views, guys, thank you... 

Danilo, what is your opinion? 
(I did not sleep well today night, now I understand why ;)

**Comment by df8oe** [comment]
OVI40-UI F7 and H7 already can work with mcHF RF and are in preparation for running with OVI40 Rf hardware - so not a problem. All other deveices where UHSDR are used are hardware compatible to one of the already supported hardwares (eagle, sparrow, RS918, RS9128)... You can use 320x240 or 480x320LCD on all UI boards without compiling anything new. All is done via life time detecting.

**Comment by db4ple** [comment]
Spoiler: This is way too long!
Here we go:
Actively we support indeed just 4 configurations, because the four configurations covering almost all devices running UHSDR which are thousands if we counted correctly.

Supporting many different configurations is difficult. Especially if you don't own devices matching these configurations. For instance we had this nasty bootloader bug showing up on a specific subset of device but on none of the developers devices. We had to get access to such a device in order to find the root cause. 

So having a software running on a lot of different hardware devivces as such is not necessarily helpful for both sides (the users and the developers/supporters). 

In this light one of the decisions to keep complexity in check was not to consider new microprocessor platforms unless there is a good reason or need for this. At this moment, I personally (!) think, with the F4 upto the H7 we have a reasonable range of power available for the main processor if we keep it at an embedded project. We are not even close to unleash the power of the H7 platform on the application level (for instance no SD card support for instance to record QSO or IQ data and play it back / transmit it).
This is where I see our challenge and need for more flexibility and innovation, on the application layer. 

I can some of you hear now: This would be much easier with a full fledge operating system which comes with a lot of low level services such as processes, file input/output and a wide range of hardware drivers. If we are not looking for the smallest amount of power usage, a Pi Zero with Linux can do this job quite well (if the power budget is larger, get a PI 3). For some of the real time processing, the Pi is probably not too well suited, here an HW platform such as the STM32 can fill the gap nicely. So we are back to where we started.  

Honestly, most user really don't care what processor is in such a standalone TRX. Is a NXP better than a STM processor? I don't think so. There are differences, but not too significant. So porting to a new embedded processor platform is of interest to some of us but at the moment does not add value for most of us. 

Which does not mean I don't find this interesting having a background as developer of embedded real-time OS. We ported the OS to anything which had pins sticking out, back in the 90s, ranging from 8bit to 32bit controllers. So I have an idea how to do this. The biggest challenge was never the processor but the peripheral support. We did this in C++, which was nice, but I am not interested to do repeat this in plain C. One of the reason I like to use the HAL. Without the HAL and CubeMX we would still be reading the 3000+ pages of STM32H7 documentation. If we would have waited for a "real" RTOS with a lot of device drivers to pickup the H7, I don't know where we would be now, either.  

What I am interested in, though, are changes to help us to better test devices, which can be by the way of (automated) tests running on a PC. or on the devices with some kind of instrumentation or running in an emulated processor. An easy to use abstraction layer for this could be very helpful especially for developing DSP code.

This is where I could see a reason for introducing a better abstraction from the lowest levels of hardware handling (a PC does not provide the same peripherals as an STM32F4 and is normally not able to drive any of our RF hardware).

To make a long comment short:
The Universal in the name of UHSDR can be interpreted in several ways. I personally think it should represent the ability to interact with different hardware concepts (such as DDC or IQ capture via QSD/QSE, QRP or  not, different screens, different ham modes and applications supported). Of course it will not be a truely universal thing. See how many companies stick for very good reasons to a single processor family just because this saves so much work and makes it possible to reuse a lot of knowledge.

I see it also to provide a platform to try out new concepts. Most of this does not demand a different processor family to be supported so you can build your ideas on existing concepts and hardware.

I think we can achieve more if we accept that we don't get all we want (I personally would like to switch to C++) but we also have to respect the opinion and interest of others and the value they bring to this. Essentially I have for instance only a very limited knowledge of DSP (like most of us) but there are some experts here who did great things in this area because of their in-depth knowledge of this area. But from the pure software developer perspective they did not do always that great in some aspects of the implementation due lack of knowledge and experience. Should we make them go by introducing "better" software concepts which require skills to master they don't have the time and/or interest to accquire? This is a tough one.

Concretely, maybe we are too afraid to introduce more complex concepts (I am talking about threads, concurrency, and multiple levels of abstraction) and underestimated the benefits and overestimate the risks. I am happy to have a discussion on this. 

One of my main personal objectives here in this project is to help building a long lasting larger community of developers with different skills around the UHSDR. This is not trivial, as it turns out and maybe we are not smart enough to do it right. However, many open source projects fail on this and are run by only one or two persons. We managed to involve a few more in the last years. We also lost some, I guess.

It may seem that the current group of developers is hostile and not willing to let someone with more skills in unless he or she is exactly following our way of thinking. This is surely not true from our intents. And I would not write such a long text if I wouldn't be interested in getting you (Max and other skilled developers) in. But as in every group, you have work for your reputation. It does not count what you do or did elsewhere, it counts what you want to and are able to add to this project as value in consensus with the "voices" of the group. 

Finally, if you think we are a stupid bunch of dickheads (which we, to a certain degree, probably are) and only waste your time, well, the beauty of free software is, you don't have to work with us to benefit from what has been done as long as you follow the rules of the GPL. And you can make us look stupid by doing great stuff with the software with any of us having any right to discuss this with you. Don't think this is your best choice, but it is a valid choice.

I am happy to also have a more private discussion, just register in either the Sulingen I40 forum (preferred) or in the Yahoo NG and send me or some of us a personal message/email.

**Pull request merged**
