### PR TITLE
Implemented a Codec I2S Restart Function

### PR DESCRIPTION
**Pull request by db4ple**
And did some cleanups. No functional change except for restart function

### CODE REVIEW

**Comment by PA3CCE** [comment]
Op 19-6-2016 om 16:50 schreef db4ple:

> And did some cleanups. No functional change except for restart function
> 
> ---
> - Implemented a Codec I2S Restart Function, which can be activated
>   by the user via standard menu (Restart Codec).
> 
> Hi

Does this mean there was a bug in the firmware ?
I'm searching for days to find the cause of my mcHF having no Rx audio 
output,
while the spectrum display shows normally.
It looked like the audio was muted by the firmware, but I saw nobody 
complain, so....

73 de Jos

**Comment by db4ple** [comment]
No, there is no issue related to the audio output. There is an issue with the IQ stream (which is technically also an audio stream) but the issue does not mute the audio or anything. Your problem is something else but there have been no reports of muted audio so I guess your problem is a configuration issue or a hardware issue (try to see if you have line out audio or USB audio signal).

**Comment by PA3CCE** [comment]
Op 20-6-2016 om 13:35 schreef db4ple:

> No, there is no issue related to the audio output. There is an issue 
> with the IQ stream (which is technically also an audio stream) but the 
> issue does not mute the audio or anything. Your problem is something 
> else but there have been no reports of muted audio so I guess your 
> problem is a configuration issue or a hardware issue (try to see if 
> you have line out audio or USB audio signal).
> 
> OK, thanks for the reply.
> Strange thing is, I see the IQ signals on the input of the WM8731 
> (LLINEIN/RLINEIN), but just some noise on the output (LHPOUT/RHPOUT).
> It happend after having worked correctly; I have replaced  the device 
> but no luck.
> Will keep on searching.

**Comment by PA3CCE** [comment]
Op 20-6-2016 om 13:35 schreef db4ple:

> No, there is no issue related to the audio output. There is an issue 
> with the IQ stream (which is technically also an audio stream) but the 
> issue does not mute the audio or anything.
> 
> I'm still searching for the cause of my audio problem.
> Today I flashed the latest daily snapshot (21/06)  and used the new 
> codec restart from the menu.
> When I activate this, the "Do it!" text flashes and after that, a red 
> "R" shows before it as a remains from the previous (unreadable) text.

I have a signal generator connected to the antenna input of the mcHF 
tuned to 7.000.000MHz.
I have the mcHF set to 7.001.000MHz LSB and it shows a bit less then S9 
+40 dB and -78dBm/Hz (a contradiction).
The spectrum scope shows a high peak.

Sometimes, rather often, it shows 2 peaks (very poor image rejection) 
and when I use the new codec restart, the second peak has disappeared;  
I guess this is why you implemented it.

I should hear a 1kHz tone from the speaker connected to the speaker out 
connector (J4), but I don't.
I do hear this tone from the line-out connector (J1).

These are the results of my measurements on the codec WM8731 (U1) :
I and Q signals (LLINEIN and RLINEIN) :  both  11 kHz,  567 mVtt
Audio out on RHPOUT :                              1kHz,  194 mVtt
Audio out on LHPOUT :                               NONE !  (just some 
noise)

The only thing I can find is that the I2C2 signals from the MCU to the 
codec (SCL and SDA) are not really nice square waves on my 250MHz 
digital scope. I checked the pull up resistors R6 and R7, but they are OK.

I am out of ideas, please do you have any sugestions ?

vy 73 de
Jos

**Comment by db4ple** [comment]
if you hear the tone on the line out and do not hear it on the speaker, there is most likely a hardware problem. Inside the Audio Codec the speaker output is connected to left headphone out, line out to the right headphone out. The digital stream is delivered correctly otherwise you would not hear anything on the line out. Check U2 pin 3 (here the signal should arrive). And pin 5 is the output. Try to use headphones on the phone jack to see if the signal arrives there. Since the jack switches the speaker signal off if a headphone is plugged in, there is a chance that the switch fails and thus no signal on the speaker. I seriously doubt this being a firmware issue.

**Comment by PA3CCE** [comment]
Again, thanks for the reply.

In my previous message I told you that I measured the signals DIRECTLY 
on the codec,
there really is NO signal coming out of LHPOUT (pin9) of U1.

I have my external speaker connected to the "Phones" connector (J4), not 
to the header
for an internal speaker, so no problem with the internal switch of J4.

I even interchanged LHPOUT and  RHPOUT (pin9 and 10) of the codec, then 
the audio
comes out of the speaker OK, I just can't control the level by the 
encoder, but the Rx
is performing normally.
So the speaker amplifier U2 and all after is OK.

As said, it has been working correctly before and I already have 
installed a new WM8731
with the same result. I'm asking myself, if I have to do this again !

Jos

**Comment by db4ple** [comment]
Hi Jos,
sorry I missed to see that you did all of that already (I answered to your reply from 2 days ago). Mea culpa. 
Last question on the HW side, just to be sure: Could there be a solder bridge etc. to GND from LHPOUT,i.e. Did you check continuity from Pin 9 to GND? 

If it would be a general FW issue, there should more issue reports. Did you try to flash an older firmware to see if it is giving the silent speaker as well? If it is I2C related, why would it consistentenly break the just break the left out and nothing else? 

73
Danilo

**Comment by PA3CCE** [comment]
Op 22-6-2016 om 14:43 schreef db4ple:

> Hi Jos,
> sorry I missed to see that you did all of that already (I answered to 
> your reply from 2 days ago). Mea culpa.
> 
> No problem.
> 
> Last question on the HW side, just to be sure: Could there be a solder 
> bridge etc. to GND from LHPOUT,i.e. Did you check continuity from Pin 
> 9 to GND?
> 
> Yes, I did, no short.
> 
> If it would be a general FW issue, there should more issue reports. 
> Did you try to flash an older firmware to see if it is giving the 
> silent speaker as well? If it is I2C related, why would it 
> consistentenly break the just break the left out and nothing else?
> 
> This was my idea also.
> I will flash the latest stable version and let you know the result.
> As a matter of fact it happened shortly after I replaced the MCU for a 
> new one with more memory, it performed well for a short time, then 
> suddenly the audio stopped. I don't see how the MCU could be the cause.

73 Jos

**Comment by PA3CCE** [comment]
Hi Danilo,

Well, I flashed the latest stable version of the firmware (15th of May) 
but still the same problem, as expected.
When I turn the Audio Level encoder, I hear clicks out of the speaker 
with increasing level, but no audio at all.
regards
Jos

**Comment by db4ple** [comment]
Assuming you have an I2C EEPROM:
1. Go to Standard Menu -> Backup Config 
2. Restart, press F1+F3+F5
3. Select to reset to default
4. See if Audio is available
   If this experiment resulted in a success, you problem is somewhere in  the configuration.
   If you just cut the power, your old configuration is restored and you can try to dig around there.
   If you do not have an EEPROM, skip step 1, but make very sure to cut the power instead of pressing power, otherwise your  old configuration is lost forever. If  you executed step 1 your old configuration can be restored from the menu, even if you accidentially pressed Power.

73
Danilo

**Comment by PA3CCE** [comment]
Danilo,

Yes I have an EEPROM, so I saved the configuration and loaded the 
default configuration.
After this, no change, no audio.
Reloaded my original configuration.

73
Jos

**Comment by db4ple** [comment]
Hi Jos,

I am sorry, but I have no idea what could cause this from the software side. If the default configuration does not bring audio on the left channel back and the right channel works, I have no clue at all. Especially since you already  exchanged the audio codec.

**Comment by PA3CCE** [comment]
> Hi Jos,
> 
> I am sorry, but I have no idea what could cause this from the software 
> side. If the default configuration does not bring audio on the left 
> channel back and the right channel works, I have no clue at all. 
> Especially since you already exchanged the audio codec.
> 
> It's the same with me.
> I think that I will replace the codec again, that's my only hope.
> Thanks for your time.

73
Jos

**Comment by PA3CCE** [comment]
@ Danilo

I Installed a new unused codec, now it's not working at all !!! :'(
They all came from China, so ????
I'm searching for a decent supplier, Conrad does not sell, Mouser needs 
$20 for a $5 device, Farnell likewise.

Best regards
Jos

**Comment by df8oe** [comment]
Hi Jos,

is there audio when you shorten pin9 and pin10 of audio codec during operation? Of course at codec where audio works on line out...

vy 73
Andreas

**Comment by PA3CCE** [comment]
Op 24-6-2016 om 13:12 schreef DF8OE:

> Hi Jos,
> 
> is there audio when you shorten pin9 and pin10 of audio codec during 
> operation?
> 
> vy 73
> Andreas
> 
> Hi Andreas,

Well, this time the codec does not work at all, so no display in the 
spectrum, so I guess not.
I don't know if you followed the discussion, but with the previous one I 
had audio on pin 10 and NO audio on pin 9.
Ther was no short on pin 9, so I guess there was audio when I shorted them.
Dos this answer your question ?

vy 73
Jos

**Comment by PA3CCE** [comment]
I could replace the codec by the previous one to see if it replicates, 
but I don't want to screw up the PCB.

**Comment by db4ple** [comment]
Hi Jos,
I recommend to get a decent Codec, maybe the eBay Seller just sents out defective IC. Maybe you ask in the Yahoo group or the German Forum (http://www.amateurfunk-sulingen.de/forum/index.php?board=15) for someone with a spare codec from a reliable source. Your story should also warn off others.

**Comment by PA3CCE** [comment]
Op 27-6-2016 om 9:42 schreef db4ple:

> Hi Jos,
> I recommend to get a decent Codec, maybe the eBay Seller just sents 
> out defective IC. Maybe you ask in the Yahoo group or the German Forum 
> (http://www.amateurfunk-sulingen.de/forum/index.php?board=15) for 
> someone with a spare codec from a reliable source. Your story should 
> also warn off others.
> 
> —
> 
> Hello Danilo,

Today, after some delay, I restarted debugging and found the cause of 
the problem.
The cause was not the Chinese codec but it appeared to be a short to 
ground under C7a,
which was replaced by a 0 Ohm resistor.
(LOUT, Codec Pin13, was grounded, so muting LHPOUT).
C7a is located on top of the UI PCB closely to the right of the LCD.

Just wanted to let you know.

73 de
Jos

**Comment by db4ple** [comment]
Thanks for the heads up. So it seems, the eBay provided codecs are good ones as well.

73
Danilo

**Pull request merged**
