### PR TITLE
XVTR Offset up to 1999000000Hz for Transverter use e.g. new TRX Lapwing

### PR DESCRIPTION
**Pull request by ghost**
Transverter Offset XVTR extended for values up to 1999000000Hz.
Frequency display extended by the GHz digit.

### CODE REVIEW

**Comment by db4ple** [comment]
To help us understanding the impact of the change:
Did you check it fits on the 320x240 / 480x320  small and big display in normal and split mode?.

**Comment by ghost** [comment]
320x240 Display cannot be tested.
480x320 Display: In split mode the large GHz digit remains visible, this must be corrected.

**Comment by df8oe** [comment]
320x240 working is mandatory. Or you must change the code that it can only be accessed if 480x320 is detected.

**Comment by ghost** [comment]
Okay, then I'm out!
I have no possibility to test on the 320x240 display.

**Comment by df8oe** [comment]
Haven't you read the second possibility:

- only activate this feature when a 480x320 display is detected?

**Comment by m-chichikalov** [comment]
What if evaluate the space needed for freq. and accordingly decide which font to use?

**Pull request closed without merging**
