### PR TITLE
Fix for Tune Power is not set correctly if not equal to current TX power (#1750)

### PR DESCRIPTION
**Pull request by db4ple**
we better tell the function which power we really want...

### CODE REVIEW

**Comment by df8oe** [comment]
After I merged this former funcionally "Tune Power" is destroyed again...

**Comment by db4ple** [comment]
I have to check this again then.

**Comment by df8oe** [comment]
Additionally: I do not see why my solution calls a function twice. It calls setting power at the beginning of transmission  (to set to desired level - setting of power is missing now) and then when going to RX it sets back to "standdard TX level".

**Comment by db4ple** [comment]
I cannot see the issue reappear after line removal. 
It is working now as intended. I am building a 2.11.45 from unmodified source code.

The second call is "hidden" in the RadioManagement_SwitchTxRx() call.
You can check that with a ST Link, if you don't trust me and the code :-) . 
I was not saying it is obvious.

**Comment by df8oe** [comment]
My build from source code of 2.11.45 tunes again with standard TX power and ignores TunePowerLevel while 2.11.44 works...

**Comment by df8oe** [comment]
Maybe the value that is used in RadioManagement_SwitchTxRx() is the wrong one...

**Comment by db4ple** [comment]
I debugged the function using ST-Link and it is using the correct one and the power meter also shows the right value. I'll test the official build this night and see if it behaves differently.

**Comment by df8oe** [comment]
The meter is showing correct value in every case - but transmitting is always with "normal TX power" instead of "Tune Power"

**Comment by db4ple** [comment]
How can the integrated watt meter (I think we are not talking about the xxW blue box), which measure the actual power output via ADC show the "correct"  value but the real output power is wrong.  The wattmeter measurements function / code is not related to the power.

I'll check this.

**Comment by df8oe** [comment]
Integrated wattmeter does not show anything - it is always "0". I only can check at mcHF because all of my OVI40 boards are connected to experimental rf parts which do not have any PA stages.

**Comment by df8oe** [comment]
Sorry - I have written misleading - I do mean TX power value display

**Comment by df8oe** [comment]
Now for absolute clarifying this result for 2.11.45:

- Power value in display shows correct TX power in normal TX and in Tune function
- Power meter does show "0" (no bars) in all cases
- TunePower is always as normal TX power regardless of TunePowerLevel setting

tested with mcHF STM32F439 MCU and mcHF rf PCB.

**Comment by db4ple** [comment]
My wattmeter (on OVI40 UI/ mcHF RF) shows correct value (in line with power value in blue box). It also doubles measured output if I for instance set tune to 2W instead of 1W. 

How do you measure the output power? With an external wattmeter?

**Pull request merged**
