### PR TITLE
hex2dfu changes for python3

### PR DESCRIPTION
**Pull request by csylvain**
my system is prepared for building fw and has only Python 3.
these changes update the tool used in the UHSDR fw build recipe.

### CODE REVIEW

**Comment by df8oe** [comment]
It is a very good idea to implement python3! But because there is many, many stuff that has not migrated to python3, python on most systems targets python2 (so on my bleeding edge "Siduction" that bases on Debian experimental). So I think it would be wise not to point to
/usr/bin/env python
but to
/usr/bin/env python3...

**Comment by csylvain** [comment]
suit yourself (as in: suits me fine either way). i've had too many headaches keeping both pythons around. whenever i can, i now leave python2 out of the picture. helps to move the migration along, yes?

**Comment by csylvain** [comment]
made the suggested change. found something else needing a change, too.

**Comment by df8oe** [comment]
You have to look again. .dfu-files are much too long - there is definitely something going wrong... Normally difference between bin and dfu is max. 500 bytes. The now created dfus are more than 11KB large (bootloader build)...

**Comment by csylvain** [comment]
okay.  will have to be much more in depth than fixing syntax problems.
with 2.11.78 and python3, i have
```
$ du -sh fw-*
420K    fw-mchf.bin
572K    fw-mchf.dfu
2.7M    fw-mchf.elf
768K    fw-mchf.map

**Comment by csylvain** [comment]
with 2.11.78 and python2, i have
```
$ du -sh fw-*
420K    fw-mchf-python2.bin
420K    fw-mchf-python2.dfu
2.7M    fw-mchf-python2.elf
1.3M    fw-mchf-python2.hex
768K    fw-mchf-python2.map

**Comment by db4ple** [comment]
Hi, @csylvain: 
Thanks for doing the migration to python3 
 
The issue in your changes is here:
https://github.com/df8oe/UHSDR/blob/1c64ad45e7a2b81480b24f7051cab0338ee5fd31/mchf-eclipse/support/hex2dfu/hex2dfu.py#L73
You cannot have python translate a binary string using the utf-8 encoding into a byte array. It will expand some of the binary sequences into the related utf-8 encodings which uses more bytes, hence the longer resulting binary.

A question for you: Did you test the resulting dfu files produced by your code?

Good news is, I think to get the same result on python2 and python3 a simple change will suffice:

```python
    image_data = ih.tobinarray()

    data = struct.pack(
        "<II",
        ih.minaddr(),       # dwElementAddress
        len(image_data)     # dwElementSize
    ) + bytes(image_data)          # Data
````
 
This, fortunately makes the code run on python2 and python3 with the same result.

**Comment by csylvain** [comment]
sorry, the utf-8 got added because your suggestion (which i tried at first using the ascii encoding) only produced an error indicating it was unable to create the bytes without an encoding.
now that i have created and preserved a python2 baseline, i will investigate further.

**Comment by db4ple** [comment]
@csylvain: I, db4ple, did not suggest anything. But the important thing is to switch to use `ih.tobinarray()` instead of `ih.tobinstr()`, which allows to use bytes() without re-encoding.  
BTW, the makefile calls the script with /usr/bin/python and bascially ignores the #! setting.
But with the script running on both python2 and python3 there is no problem with that.

**Comment by csylvain** [comment]
i thought i recognized the code snippet and also that you were pointing only at the bytes() call.
in that stanza, then, there were two changes to make and i made only one. okay, then.
shall i work up a new pull request against 2.11.78 ?
also, as someone may want to call hex2dfu on it's own, i will leave the python3 on the hashbang line.

**Comment by db4ple** [comment]
@csylvain: No problem, my fault. But again, good job. You should have tested the resulting dfu, though.
@df8oe: Good job spotting this.
BTW, despite my previous message, the code does not run on python2 and python3 in identical form.
Pyhon2 -> ih.tobinstr plus bytes works, ih.tobinarray produces very large output
Python3 -> ih.tobinarray plus bytes works, ih.tobinstr requires encoding in bytes and produced wrong output.

**Pull request merged**
