### PR TITLE
Added default UI and RF boards defines to handle make all.

### PR DESCRIPTION
**Pull request by m-chichikalov**

### CODE REVIEW

**Comment by df8oe** [comment]
Why not going this way:

ifndef CONFIGFLAGS
  CONFIGFLAGS=-DUI_BRD_MCHF -DRF_BRD_MCHF
endif

??

**Comment by m-chichikalov** [comment]
It's almost the same as the assignment to CONFIGFLAGS ignored by make if this parameter passed as an argument. But, sure I can add, maybe it's more clear to read when there this extra "ifndef"...

**Comment by df8oe** [comment]
...it's more clear to read when there this extra "ifndef"...

Yes, that's my opinion, too...

**Comment by m-chichikalov** [comment]
Done.

**Comment by m-chichikalov** [comment]
Wait, there is some error in the building, do not accept. I need to go, will fix later.

**Comment by m-chichikalov** [comment]
@df8oe , Andreas, you can accept, I've just built it in different branch :)

**Pull request merged**
