### PR TITLE
Config Menu refactoring done

### PR DESCRIPTION
**Pull request by hogthrob**
At least stage 1 :-)

### CODE REVIEW

**Comment by df8oe** [comment]
I must review this - will take some time. Meanwhile an issue occured (powering down when DSP is enabled lasts minutes). I fixed this and fixed some minor problems in config and standard, menu too. Now not automatically merging is possible - plse be patient, I will select and merge.

vy 73
Andreas

**Comment by df8oe** [comment]
OK - I have merged manually. Please do a pull to get new version.

**Comment by hogthrob** [comment]
Thanks.

**Comment by df8oe** [comment]
Some small issues - I think you can fix them faster than me...

1) in menu #209 there are missing many colors and when you step down or up its not the same
2) in menu #207 you can select time - but no longer "off"

We are gettting near to a "perfect menu" (in working AND view :)

hope it is a small fix - I am testing further more

vy 73
Andreas

**Pull request closed without merging**
