### PR TITLE
added file local vars for explicit emacs support on code style

### PR DESCRIPTION
**Pull request by HB9ocq**

### CODE REVIEW

**Comment by df8oe** [comment]
This do not build. Something is going wrong in hy28b_fonts.c - please have a look, correct it and send pull request again.

Hint:
When looking at Travis Cl build you canget more details. I think there is something wrong with character encoding. (UTF-8?)

vy 73
Andreas

**Comment by HB9ocq** [comment]
I beg for pardon, it slipped past my attention. Done.
I did not expect a compilable C source file to begin with unprintable, non-ASCII <U+FEFF>.
Then just inserting a C Comment line at the beginning makes it UNcompilable.

**Comment by df8oe** [comment]
Not a problem. But I want to spend as less time as possible to manage ull requests ;)

vy 73
Andreas

**Comment by HB9ocq** [comment]
Sure. My fault = I fix it!  :-)

**Pull request merged**
