### PR TITLE
 Finishing of VSWR Protection PA

### PR DESCRIPTION
**Pull request by satoryboy**
Please merge only commit 0f0b786 "Finishing of VSWR Protection PA".

### CODE REVIEW

**Comment by df8oe** [comment]
Your pull request has conflicts - I think because of you don not have rebased properly in the past. So please first solve the conflicts.

**Comment by df8oe** [comment]
Hi Satoryboy, sorry. I do only merge if it is structured (no comments like ...maybe thiy way...), does not contain reverts and has no conflicts. There is more than one way to reach this. Because of your changes are minor you simply can firstly go to the same stage as the repo (OK - your changes are lost now). Then you add the lines and commit them with a nice comment. This is quite simple. But there are some other ways (which would be better if the changes are bigger).

**Comment by satoryboy** [comment]
Hi. I was said - I'm not good coder (1S etc and little about C), sorry. Please delete my last pool request. I learn "Git for Windows". Most problem - how to made my forked repozitory actual to base repozitory for commit (clone new repozitory - not good way). All is simply, but I need some time. It's not the last change of FW from me. I begin the project about calibrate of LO suppression on every band via DACs. Thanks for your help and cooperation.





>Понедельник, 25 февраля 2019, 22:05 +05:00 от DF8OE <notifications@github.com>:
>
>Hi Satoryboy, sorry. I do only merge if it is structured (no comments like ...maybe thiy way...), does not contain reverts and has no conflicts. There is more than one way to reach this. Because of your changes are minor you simply can firstly go to the same stage as the repo (OK - your changes are lost now). Then you add the lines and commit them with a nice comment. This is quite simple. But there are some other ways (which would be better if the changes are bigger).
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Юрий Коренев

**Comment by df8oe** [comment]
I think here is the answer to your problem:
https://stackoverflow.com/questions/1628088/reset-local-repository-branch-to-be-just-like-remote-repository-head

**Comment by satoryboy** [comment]
Thank you very mach. I'm really old man, learning is difficult to me ))/



>Вторник, 26 февраля 2019, 22:30 +05:00 от DF8OE <notifications@github.com>:
>
>I think here is the answer to your problem:
>https://stackoverflow.com/questions/1628088/reset-local-repository-branch-to-be-just-like-remote-repository-head
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Юрий Коренев

**Pull request closed without merging**
