### PR TITLE
1)added a 2nd development mode for noice reduction which does statist…

### PR DESCRIPTION
**Pull request by dl2fw**
…ical noise estimation

also during speech frames (within only noise containing frequency bins)
It doesn't depend on any voice activity detection

2)the 3 different noise reduction methods are now seperated into 3 functions.
- Release, -Devel1, -Devel2
This incorporates some redundancy but is better for further optimization
and will later be solved / optimized
For the 2nd development mode the parameters for the noise etimation have to
be optimized by further testing!

### CODE REVIEW

**Comment by DG9BFC** [comment]
how can we optimize it if the user (betatester) has no values to change?!? ... what values are available for turning up and down in menue for devel 1 and 2 ??

**Comment by dl2fw** [comment]
Hallo Siggi,
für den Devel 1 kannst Du mit Beta und der NR- Einstellung arbeiten.Für Devel2 müssen wir leider erst ermitteln (im code) welche Parameter für den User sinnvollerweise änderbar sein sollten (prinzipiell sollten das sehr wenige sein)Es gibt im Moment recht viele Eingriffsmöglichkeiten....
73 Michael 


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: DG9BFC <notifications@github.com> Datum: 07.01.18  17:50  (GMT+01:00) An: df8oe/UHSDR <UHSDR@noreply.github.com> Cc: Michael - DL2FW <micwild@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [df8oe/UHSDR] 1)added a 2nd development mode for noice reduction which does statist… (#1330) 
how can we optimize it if the user (betatester) has no values to change?!? ... what values are available for turning up and down in menue for devel 1 and 2 ??

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/df8oe/UHSDR","title":"df8oe/UHSDR","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/df8oe/UHSDR"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DG9BFC in #1330: how can we optimize it if the user (betatester) has no values to change?!? ... what values are available for turning up and down in menue for devel 1 and 2 ??"}],"action":{"name":"View Pull Request","url":"https://github.com/df8oe/UHSDR/pull/1330#issuecomment-355835746"}}}

**Comment by DD4WH** [comment]
Hi Michael,
it seems that devel2 is very promising!
Can you tell me which algorithm that is, so I can read more about that?

**Comment by DD4WH** [comment]
sorry, Michael, I already found it!

**Comment by dl2fw** [comment]
Hello Frank,
yes it really works promissing, but right now not as well as the implementation on matlab and an audio passthrough....
Be careful, the names of  the variables  in Devel1 and 2 are a bit misleading. To avoid more memory consumption I used the variables from the existing NR structures.Especially HK_old... ist not what it is called.....
regards Michael



Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: DD4WH <notifications@github.com> Datum: 07.01.18  19:44  (GMT+01:00) An: df8oe/UHSDR <UHSDR@noreply.github.com> Cc: Michael - DL2FW <micwild@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [df8oe/UHSDR] 1)added a 2nd development mode for noice reduction which does statist… (#1330) 
sorry, Michael, I already found it!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/df8oe/UHSDR","title":"df8oe/UHSDR","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/df8oe/UHSDR"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DD4WH in #1330: sorry, Michael, I already found it!"}],"action":{"name":"View Pull Request","url":"https://github.com/df8oe/UHSDR/pull/1330#issuecomment-355843043"}}}

**Pull request merged**
