### PR TITLE
Quick scan of the band

### PR DESCRIPTION
**Pull request by satoryboy**
Hold button "BAND-" or "BAND+" for skip -45 or + 45 kHz. Very conveniently for quick scan of the band.

### CODE REVIEW

**Comment by sp9bsl** [comment]
Hi Yuri,
why +/- 45kHz? We have 48kHz span with zoom=1

**Comment by db4ple** [comment]
My problem here is that these action keys may be very confusing if you are zoomed in (no matter if 48 or 45 step width) or said in other words: I don't think it makes sense to jump always by (almost) the bandwidth, shouldn't be be rather the zoom bandwidth?

**Comment by sp9bsl** [comment]
100% agree Danilo, this is good idea.

**Comment by satoryboy** [comment]
45 - for easy viewing of edges. About zoom - no problem to determine the magnify. One simple question - what's the reason to skip in zoom mode? To DP4PLE: I would not refuse of 96 kHz panorama - it is possible with codec WM8731 )).

**Comment by sp9bsl** [comment]
> One simple question - what's the reason to skip in zoom mode?

Hmm... So far I understood that you want to move receiving frequency outside the visible bandwidth of receiver. In zoom mode you see narower bandwidth because of 48kHz/zoom, so you need to divide scan step by the zoom factor, if there would be no divide you simply skip part of the band.

**Comment by df8oe** [comment]
Hi Yuri,

if you do want to appear in the "Hall of Fame" please tell me your callsign. Every Contributor who wants to be present there can get this.

Regarding button presses you can get informations what is already used here: https://github.com/df8oe/UHSDR/wiki/Operating-Manual

**Comment by df8oe** [comment]
Regarding your PR:
I see it as mandatory that step is in dependency of magnify mode. Please add this before I merge. Many OMs are running ALWAYS in magnify mode.

**Comment by satoryboy** [comment]
To SP9BSL: Hi! I don't want something complicated, just conveniently scan of the band at the beginning of work.
To DF8OE: Thanks, but I have not any callsign at this time (ex UA9YPF). I plan to get it in summer. While preparing the technique (tx only to dummy load ))  ). Sorry of my bad english. About button presses: I see in the code - holding press "BAND-" and holding press "BAND+" separately is free of any actions (on my rig also). If possible, I want to use their for actions as in this pool-request.

**Comment by df8oe** [comment]
I can add your name without callsign and add a callsign later- look at the Hall of Fame there is another entry only by name. Yes BAND buttons long press are free for usage. To avoid confusion adding magnify modes dependency to your pull request is mandatory. You can simply add it and make again a PR and the new changes are automatically added to one PR.

**Comment by df8oe** [comment]
96KHz is possible with codec - but not with STM32F4 (too low RAM).

**Comment by db4ple** [comment]
Hi,
I know Band+/Band- press and hold are not being used yet, and we don't have better memory management yet, but the Band+/- hold would be kind of natural  for switching between memories. More in my opinion than the quick movement through the band as discussed here.

As long as everybody feels comfortable with opening up this discussion when we are getting there, I onethe other hand have no trouble to assign the buttons for now to the band movement. But maybe someone has already a better idea now.

**Comment by sp9bsl** [comment]
It seems we have too low number of keys :)
Anyway, this functionality as proposed we already have, by pressing the spectrum area near the edges, not so convenient as key but useable...

**Comment by satoryboy** [comment]
To DB4PLE: I'm so sorry. Exuse me - I am novice in this project. OK, will use touchscreen.
To DF8OE: Thansk a lot. My name is Yuri. Please add temporary "ex UA9YPF". It's an honour for me. I hope to be useful to the project in the future.

**Comment by db4ple** [comment]
Hi Yuri,
my comments were not meant as "criticism", just as comments how to improve the solution and get it better maintainable. We do appreciate your enthusiasm and interest in the project. It is much easier to get you up to speed now, while you do small contributions.

**Comment by satoryboy** [comment]
To DB4PLE: Thanks a lot for your comments. I love criticism, really. And piously respect the principle of xiao - do not interfere in the games of serious guys. Hope to be useful.

**Comment by df8oe** [comment]
@satoryboy : I will add you to the Hall of Fame at the next release of binaries.

**Comment by satoryboy** [comment]
Please close this pool-request.

**Comment by db4ple** [comment]
Hi Yuri, I think you did not mean close, do you? I think Andreas will accept it and merge it. 

One more tip: You don't have to revert your previous changes in order to update your pull request. You just continue to make changes until you (and possibly the maintainers) are satisfied and push them into your GitHub repo branch.  Less work, same result.

**Pull request merged**
