### PR TITLE
First commit for keyer mode implementation

### PR DESCRIPTION
**Pull request by phaethon**
This is the start of the keyer mode implementation as discussed in #1002 
Long press on M1 (if not in menu mode) switches to-from keyer mode. In keyer mode F buttons are remapped:
F1-F3: keyer buttons BTN1-BTN3 (short press plays, long press records)
F4: deletes last character from buffer on short press, deletes buffer contents on long press
F5: switches tx/rx mode in buffered mode, on long press - switches on/off buffered tx on 
This PR implements only mode switching and button labels. 
@db4ple , please, consider using for RTTY.

### CODE REVIEW

**Comment by df8oe** [comment]
@phaeton: Would you please be so kind and add operating instructions to our WIKI?

**Comment by db4ple** [comment]
Hi Eriks,
thanks. Please try not to work in ui_driver.c in existing functions for the moment I have made significant changes to the way how keyboard and touchscreen events are processed. I will need to integrate your changes carefully as the functions you changed no longer exist in their previous form (as you have used them).
On the other hand, implementing alternative keyboard functions will be much easier.

BTW, please remember, we strongly ask users to use regular rebase throughout the development of their changes instead of merge of changes at the end of the own development.

**Comment by phaethon** [comment]
@df8oe I will add instructions to Wiki as soon as I have the first implementation of the actual buttons.
@db4ple The only part of existing button functions that I plan to touch in short term are the placeholders with //NOT IMPLEMENTED. That was half of the reason for the commit - to make it easier to merge. I will try to switch to rebasing from now on.

**Comment by AsbjornPettersen** [comment]
I see that 2 variables have been added in TransceiverState:

bool keyer_mode; // disable/enable keyer mode for F1-F5 buttons
bool buffered_tx; // disable/enable buffered sending for CW and digital modes

There are hundred of items in TransceiverState and if buffered_tx only shall be used for "keyer_mode" a struct should be made:

struct f_keyermode
{
	bool keyer_mode; // disable/enable keyer mode for F1-F5 buttons
   	bool buffered_tx; // disable/enable buffered sending for CW and digital modes
};
struct f_keyermode fkeyer;

When keyer_mode is set to false, the buffered_tx also should be set to false !?

**Comment by phaethon** [comment]
No, these are not related. There could be buffered tx without keyer, and vice versa. 
Buffered tx is related to digital text mode sending. We can merge it in struct with other digital mode variables.
Keyer mode is related to menu mode as it also remaps f1-f5. Actually menu mode could be renamed into eg interface_mode with values 0,1,2 dropping keyer mode entirely, but I am not sure if we want this. Although, it could look nicer in F button processing with a switch instead of cascading ifs.

**Comment by db4ple** [comment]
Please review the changes in my pull request #1027. I prepared an "empty" set of keyactions_keyer. I think you will quickly get the idea. A KEYACTION_NOP  is a NOP but does mark this key press as being processed, KEYACTION_pass leaves the key as being unprocessed, i.e. in another list which is being processed later, this key may still trigger an action.

What is not yet handled well is the update of the respective Fx key labels, but I am not too concerned about this right now. 

BTW, please respect the code style as used in the project so that we do not have mixed styles of parenthese etc. We are all asked use the same formatting, even it is not our personal preference (it would not be mine, to be honest). Acceptance of compromises is a vital part of successfull collaboration.

**Pull request merged**
