### PR TITLE
CW via DTR: Fix for previous pull request. Now working as expected.

### PR DESCRIPTION
**Pull request by db4ple**
If in CW Mode, doing PTT via FT817 CAT (!!!) will allow to
key the transmitter using the (virtual) DTR of the CAT serial port.
This has been tested with UCXLOG and MAY work with other programs.

See also #773 for a little bit of discussion

### CODE REVIEW

**Comment by WD8BXS** [comment]
I Installed the UCXLOG, and I can't even get it to copy CW, it keeps telling me that there is no output sound card found

**Comment by db4ple** [comment]
What can I say? I have installed UCXLog and it worked. 

Here is my "Other Interfaces"  Station Settings: 

image

And for reference the "Transceivers" tab as well:

image


BTW, I have never used UCXLOG for anything but testing the CW output, so it seems I am just lucky to get it going without problems.

**Comment by WD8BXS** [comment]
OK, I got it to send CW with the MCHF,  all is well there, I did not realize that it did not copy as well , my fault there.Interesting to say the least, but not to my fancy. I will stick to the fldigi and my Aclog program hihi.  maybe fldigi will catch up and allow it to key the radio for CW and not just use audio SSB.

**Comment by db4ple** [comment]
UCXLOG is user interface wise something outside of what I would consider "normal" but it seems to have its share of users.

Re fldigi: it is open source, so shouldn't be too hard to get it doing what one wants....

BTW, anyone is invited to provide the QSK code for the mcHF. It is not hard either, we discussed this in the german forum as an option if the DTR approach wouldn't work out as expected.

**Pull request merged**
