### PR TITLE
SW4STM32 and STM32CubeIDE project

### PR DESCRIPTION
**Pull request by m0nka**
Hey,

This is an extra directory that can be used to compile the project on Windows machines with standard tools for STM32 development. I have tested to the best of my abilities (on four different computers) and seems to compile with clone, build and import, under both studios.

73!

### CODE REVIEW

**Comment by df8oe** [comment]
Hi Chris,
looks nice. Would you maintain this if issues pop up in the future (maybe because of changes at our side or of changes at the Windows applications side)? If so I will merge that. Please make a note in the Readme.md of this folder that you will maintain this and issues can be forwarded to you. I cannot maintain this because I am "Windows-free" since more than 20 years ;)

vy 73

**Comment by m0nka** [comment]
Yeah, sure. I need to add some other things later (hopefully) and i am tracking your branch anyway, so any changes i will fix and push. Thanks!

**Comment by df8oe** [comment]
OK - your contribution is welcome! I'll await the additions in the Readme.md and will merge then.

73 - stay healthy

**Comment by m0nka** [comment]
Is that text ok ?

**Comment by df8oe** [comment]
...write an issue report here at GitHub or drop me an email...

I would like to bundle all discussions firstly here. No "personal support" mandatory - believe me: I know what I am telling... ;)

**Comment by m0nka** [comment]
Done as requested.

73 and stay safe!

**Pull request merged**
