### PR TITLE
disable switch for small mcHF to not use predefined window data for s…

### PR DESCRIPTION
**Pull request by DD4WH**
…pectrum/waterfall display

There is an issue report of an mcHF producing stuttering audio #1417 . Maybe this can heal it!???
Should save considerable amount of processor load during spectrum/waterfall calculations

### CODE REVIEW

**Comment by sp9bsl** [comment]
Hi Frank,
you may disable it in uhsdr_board.h.

**Comment by DD4WH** [comment]
OK, thanks Slawek, will change that :-)

**Comment by df8oe** [comment]
I suggest that does not change anything for the reported noise - but reality will show :) I wait for correction PR.

**Comment by DD4WH** [comment]
Hi Slawek, hi Andreas,
you are absolutely right: the small mcHF already uses the const windows!
I was confused by the "#ifndef" vs "#ifdef" :-)
So I close this pull request!
73 Frank

**Comment by sp9bsl** [comment]
USE_PREDEFINED_WINDOW_DATA is not used for SMALL_BUILD.
If you want to enable it for all types, simply move it outside the "#ifndef IS_SMALL_BUILD"
Yes those "#ifndefs" sometimes are misleading :-)

**Comment by sp9bsl** [comment]
If there is not enough horsepower available they should stop drawing of scope/wfall by simply go to MENU.

**Pull request closed without merging**
