### PR TITLE
Last changes for VSWR Protection PA

### PR DESCRIPTION
**Pull request by satoryboy**
Little corrections and storing to EEPROM

### CODE REVIEW

**Comment by db4ple** [comment]
Hi Yuri,
please let us guide you to have an proper pull request. I will give you instructions, and we'll get you there step by step. Once you completed a step, we'll take next one.
Step one:
- Install the git command line tools for Windows: https://git-scm.com/download/win

Let us know, once you finished this.

**Comment by satoryboy** [comment]
Good evening. I was download and install Git 2.21.0.


>Суббота,  2 марта 2019, 15:53 +05:00 от db4ple <notifications@github.com>:
>
>Hi Yuri,
>please let us guide you to have an proper pull request. I will give you instructions, and we'll get you there step by step. Once you completed a step, we'll take next one.
>Step one:
>*  Install the git command line tools for Windows:  https://git-scm.com/download/win
>Let us know, once you finished this.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Юрий Коренев

**Comment by db4ple** [comment]
Great!
Now:
- navigate to your folder containing the UHSDR firmware in the Windows Explorer.
- open the Git Bash using the context menu (right mouse click) on the folder icon
you should get a command line window, where you can type in commands.
- Now type `git status` 
You should get some output (and not an error message).
Try and confirm this is working.

**Comment by df8oe** [comment]
Hi Satoryboy,
any progress here? You have followed Danilos hints? This are only the first steps of an outstanding procedure...

**Comment by satoryboy** [comment]
Hi! Sorry for your waiting. I get it, no any error messages:

$ git status
On branch canopus
Your branch is up to date with 'origin/canopus'.
nothing to commit, working tree clean


>Понедельник, 11 марта 2019, 9:55 +05:00 от DF8OE <notifications@github.com>:
>
>Hi Satoryboy,
>any progress here? You have followed Danilos hints? This are only the first steps of an outstanding procedure...
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Юрий Коренев

**Comment by m-chichikalov** [comment]
Hi Юрий...
Could you show me the output of command 'git branch -a'?

Just need to know do you have remote repo added already or not. and know the name of it to help you farther...

**Comment by satoryboy** [comment]
Hi.


user@Armada_64 MINGW64 ~/Documents/GitHub/UHSDR (active-devel)
$ git status
Refresh index: 100% (2470/2470), done.
On branch active-devel
Your branch is up to date with 'origin/active-devel'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified: mchf-eclipse/drivers/ui/menu/ui_menu_structure.c
no changes added to commit (use "git add" and/or "git commit -a")
user@Armada_64 MINGW64 ~/Documents/GitHub/UHSDR (active-devel)
$ git branch -a
NextStep
* active-devel
remotes/origin/HEAD -> origin/active-devel
remotes/origin/NextStep
remotes/origin/active-devel
remotes/origin/active-devel-using-old-libs-obsolete
remotes/origin/archive
remotes/origin/cubemx-port
remotes/origin/devel-DF8OE-obsolete
remotes/origin/gh-pages
remotes/origin/lcd-experimental-obsolete
remotes/origin/master-obsolete
remotes/origin/testing-obsolete
remotes/origin/wip-sp9bsl-4-new-lcds
remotes/origin/wip/cleanup
remotes/upstream/active-devel
remotes/upstream/active-devel-using-old-libs-obsolete
remotes/upstream/archive
remotes/upstream/cubemx-port
remotes/upstream/devel-DF8OE-obsolete
remotes/upstream/gh-pages
remotes/upstream/lcd-experimental-obsolete
remotes/upstream/master-obsolete
:


>Четверг, 14 марта 2019, 7:19 +05:00 от Maksim Chichikalov <notifications@github.com>:
>
>Hi Юрий...
>Could you show me the output of command 'git branch -a'?
>Just need to know do you have remote repo added already or not. and know the name of it to help you farther...
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Юрий Коренев

**Comment by DmtryJS** [comment]
Hello db4ple. 

Please tell what is wrong with the merge request? Why him need to install git if the changes in the Yuri branch already exist and they are fixed? Sorry for my English)

**Comment by db4ple** [comment]
@DmtryJS Because such a small change should not be done using 6 commits like this. And this is obviously a problem of using git properly (which is not trivial). 

@satoryboy  
What you have to do is:
Start the git bash on your repository. Execute the following commands one after the other. Make sure none of this report any errors. If they report an error: Stop and post the error here.
Below the commands I am going to explain what these do.  Please read before executing the commands.

```
git stash
git checkout canopus
git reset --hard f4893575f247fb9a1a4ed2151b7a5a4ec1d78dfa
git reset --soft  5051ce7da419c767166c9353d5b739c90bb76803
git commit -m "Last changes for VSWR Protection PA"
git push -f origin
```
1. Store all locally changed files in the stash (we will get them back later). This command fails if there is nothing locally changed, so you can ignore this failure.
1. Checkout the correct branch. 
1. Make the specific commit the head of "canopus" branch. It will reset all files to the state of this change. I.e. you loose all changes you may have made after this commit. 
1. Make the specific commit the head of the branch but keep all changes made between this and the former head in the files.
1. We now put all the changes between the new repository branch head and your files on disk into a single new commit.
1. We bring your github branch to exactly the same state as your local branch. This will also update the contents of your pull request.

If you were at the beginning at a different branch than canopus: `git checkout that_branch name`. If you successfully run `git stash` you can now reverse this by doing `git stash pop`.

For all bystanders: Yes, we could have used "Quash and Merge" in the Github UI. But we rather would like to have good looking pull requests.

**Comment by satoryboy** [comment]
Good day!
I was executed all git commands without any errors and solved all conflicts with active-devel branch.
Thank you very match for your help and your time. I learn git, but it's not trivial.


>Суббота, 23 марта 2019, 21:20 +05:00 от db4ple <notifications@github.com>:
>
>@DmtryJS Because such a small change should not be done using 6 commits like this. And this is obviously a problem of using git properly (which is not trivial).
>@satoryboy
>What you have to do is:
>Start the git bash on your repository. Execute the following commands one after the other. Make sure none of this report any errors. If they report an error: Stop and post the error here.
>Below the commands I am going to explain what these do.  Please read before executing the commands.
>git stash
>git checkout canopus
>git reset --hard f4893575f247fb9a1a4ed2151b7a5a4ec1d78dfa
>git reset --soft  5051ce7da419c767166c9353d5b739c90bb76803
>git commit -m "Last changes for VSWR Protection PA"
>git push -f origin
>
>*  Store all locally changed files in the stash (we will get them back later). This command fails if there is nothing locally changed, so you can ignore this failure.
>*  Checkout the correct branch.
>*  Make the specific commit the head of "canopus" branch. It will reset all files to the state of this change. I.e. you loose all changes you may have made after this commit.
>*  Make the specific commit the head of the branch but keep all changes made between this and the former head in the files.
>*  We now put all the changes between the new repository branch head and your files on disk into a single new commit.
>*  We bring your github branch to exactly the same state as your local branch. This will also update the contents of your pull request.
>If you were at the beginning at a different branch than canopus: git checkout that_branch name. If you successfully run git stash you can now reverse this by doing git stash pop.
>For all bystanders: Yes, we could have used "Quash and Merge" in the Github UI. But we rather would like to have good looking pull requests.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Юрий Коренев

**Comment by df8oe** [comment]
Sorry - this doesn not build. Please take a look at Travis output...

**Comment by satoryboy** [comment]
Proplem is in .../hardware/uhsdr_board.h:684. No any changes from me here. I think it's error at "satoryboy force-pushed the satoryboy:canopus  branch from ba40747 to 11db27c 12 hours ago" (dont' find line 684 here). I see the one way - discard this commit and made satoryboy:canopus branch identical to active-devel. Then I'll repeat this commit neatly without any errors. Code changes is rather little. . Sorry for my stupidity.

**Comment by df8oe** [comment]
I will close this PR and you will do a clean new one. I think you have learnt much about handling possibilities of git - that's not so bad. And: *NEVER* post your login data in public!! *NEVERNEVERNEVER*. I have deleted them from your post.

**Comment by satoryboy** [comment]
Hi, vakarimas.


>Воскресенье, 24 марта 2019, 23:36 +05:00 от DF8OE <notifications@github.com>:
>
>Я закрою этот пиар, а ты сделаешь новый чистый.  Я думаю, что вы многое узнали о возможностях git - это не так уж плохо.  И:  НИКОГДА не публикуйте свои данные для входа публично!  НЕВЕРНЕВЕРНЕВЕР .  Я удалил их из вашего поста.
>- 
>Вы получаете это, потому что вы были упомянуты. 
>Ответьте на это письмо напрямую,  просмотрите его на GitHub или  отключите тему .

-- 
Юрий Коренев

**Pull request closed without merging**
