### PR TITLE
Code for Mod: LO TX Supression by bands

### PR DESCRIPTION
**Pull request by satoryboy**
Hi, I tested my mod - LO TX Supression by bands with 2 12-bits DACs. At power 10W I have supression better 50 dB on all the bands of my mcHF rig. This mod (and code) will be work on additional bands in OVI40 also. Files about this mod:

Schematic diagram of the original prototype (TRX Eagle, SP3OSJ) - http://sp3osj.kooikerhondje.com.pl/eagle/schemat/Schematics.pdf

Schematic diagram of mod - http://wdfiles.ru/9U8c

Board Topology File for Sprint Layout 5.1 or higher - http://wdfiles.ru/e6hf

Board topology, size 33.5 x 16.5 mm - http://wdfiles.ru/9U8f

Topology layout of parts - http://wdfiles.ru/9U8g

A photo - http://wdfiles.ru/9U8h

I brought the I2C2 bus to the RF board from pins 5, 6 of the EEPROM through the free pins 21, 22 of the motherboard connector. Enjoy!

### CODE REVIEW

**Comment by satoryboy** [comment]
Сlarification - DACs is MCP4725A0T-E/CH.

Corrected schematic diagram of mod - http://wdfiles.ru/5I3w

**Comment by satoryboy** [comment]
To DF8OE, Andreas - I received callsign, UB8JDC. Please fix my info at HoF. Thanks.

**Comment by satoryboy** [comment]
Please reject this pull request. I have a new one - opening allowable TX on CB bands (if ON in Debug menu). No any increase of config!

**Comment by df8oe** [comment]
We will not accept enabling TX on CB band in any circumstance. There is no country in the world where it is legally to TX on CB band with homebrew devices.

vy 73
Andreas

**Pull request closed without merging**
