### PR TITLE
Logo + Makefile cleanup

### PR DESCRIPTION
**Pull request by HB9ocq**
- new
  - a logo for mcHF: blue bg like the PCBs, white fg like silkscreen depicting a schematic of a radio tune circuit w. antenna, an oscilloscope, a diode and a headset. Like real scopes, the inner bg is filled with a gray tone. 4 coloured squares linked with phosphor-green arrows symbolise signal processing software.
- change
  - Doxyfile references the logo for the generated docs
  - Makefile thoroughly cleaned up and homogenized in syntax, added built-in help (default target)

(first contribution de Stephan HB9ocq :)

### CODE REVIEW

**Comment by df8oe** [comment]
Hello Stephan,

nice first pull request :) Works fine.

But one thought about Makefile and integration in Eclipse:

Now makefile shows help when called without params. I am not sure if that can cause problems when using in Eclipse with option "use Makefile" because it is there called without params??!! I am working 100% on console so I cannot test fast...

vy 73
Andreas

**Comment by HB9ocq** [comment]
tnx for pulling and liking the logo, Andreas.

I expected comments on "make == make help" :)
As far as Eclipse -or any IDE- is concerned, just configure the project to perform "make all" (or whatever your preferred target is), same for CI.

Rationale behind my choice: POLA = Principle Of Least Astonishment + No Harm First, so albeit I clash on "make shall build the default", one hardly knows in advance what that will be and what needs/preconditions must be met for success.
Therefore I always choose "make == make help". Can't be that wrong since many CLI tools also display help UNLESS you tell them what to do.
I agree that maybe more help text or improvements on it can be made. Suggestions + pointers are welcome.

73 de Stephan HB9ocq

**Comment by HB9ocq** [comment]
Feel free to also use the logo elsewhere (eg. in the Wiki, on the splash screen of mcHF, in the Sulinger-Forum).
I made the original artwork in Inkscape, thus SVG (Scalable Vector Graphics).

Q: where in the GitHub tree shall I check it in?

73 de Stephan HB9ocq

**Comment by df8oe** [comment]
Ok. If you can set "make all" to Eclipse everything is ok. On Cl it is ok for me for many projects need "all".

A: "support" is a good place to put it in.

vy 73
Andreas

**Pull request merged**
