### PR TITLE
CW decoder experiment

### PR DESCRIPTION
**Pull request by DD4WH**
Many things in the code still not clear to me. Some decoding is being done, but I have no CW signals at the moment to test.
1 character is always being displayed in the second line, I do not know whether this is a race condition, a code error or a property of the UiDriver_TextMsgPutChar - code !?

### CODE REVIEW

**Comment by db4ple** [comment]
Hi,
it should not be UiDiver_TextMsgPutChar -> the length is limited to fit entirely on a single line.

**Comment by DD4WH** [comment]
I dont know what you mean exactly: as far as I know, the characters are sent one by one, so I expected  UiDiver_TextMsgPutChar to cope with all that!?

**Comment by db4ple** [comment]
I meant the character on the second line should not come from the PutChar call.

**Comment by DD4WH** [comment]
oh, then I will scan the code again, because I meant to only use UiDiver_TextMsgPutChar for printing. Will dig deeper into that.

**Comment by db4ple** [comment]
You don't have to scan, there is nothing in it. I did that already.

**Comment by db4ple** [comment]
Can you send a screenshot of the problem with the character on the second line?

**Comment by DD4WH** [comment]
sent you a PM, that was easiest.
The characters in the upper row scroll like they should, the character/s in the second row stay where they are. They seem to appear only the first time the character row is filled, this happens really fast.

**Comment by DD4WH** [comment]
will be busy with other things now, I can do more tomorrow :-)

**Comment by db4ple** [comment]
Hi, I checked, unfortunately, my display does not have the problem. So I cannot reproduce. However, what I found is that I had a total lockup of the TRX. Thanks to the ST-Link it was easy to find out.

Line 1144 in cw_decoder.c:

while((!DataRecognitionFunc()) && (ts.sysclock < freezetime + 2));

This will not work as expected. You are calling the CW decoder in the Audio-Interrupt. And this kind of loop will not work: the Audio-Interrupt itself is responsible for increasing ts.sysclock. So if you wait inside the Audio-Interrupt for it to change: Will not happen.  Generally speaking: Any form of busy waiting should not happen inside the interrupts. In fact, it should never be used unless there are very good reasons as this stops the other functions of the TRX to get their time. ts.sysclock increments in 10ms steps, this is very long.  
Code using such an approach is not directly usable for us.

**Comment by db4ple** [comment]
A quick scan through the code shows that the error correction function is the only one doing such "unwanted" waiting. So the rewrite has to enable us to recognize that we are in "error correction" mode and should be able to continue where it left off last time. There are three locations of such a loop in the error correction function. This is not going to be trivial.

**Comment by DD4WH** [comment]
OK. Thanks a lot for identifying! I inserted that ts.sysclock waiter assuming that it would be incremented by another interrupt and not the same interrupt it was implemented in. So I will go deeper into that and have a close look at the error correction function and what could potentially hang there.
Strange things seem to happen with my particular display hardware . . . it makes problems with the noise blanker and also with this text display, I wonder what´s going on there . . . !?

**Comment by db4ple** [comment]
I think I found a fairly simple solution to the problem. We don't need the timer, we simply can check if the function is stuck in an potentially endless loop.

I can commit a pull request containing the required changes. It is not much.

**Comment by DD4WH** [comment]
That would be great, if you could include that endless loop check!
No more chance to test the decoder and parameter settings on the bands tonight, HF conditions are extremely bad at the moment, Aurora is there and all bands seem pretty closed! ;-)
Good night!

**Pull request merged**
