### PR TITLE
Minor things

### PR DESCRIPTION
**Pull request by db4ple**
Split python code into API module and APP module the command line tool is now named uhsdr_tool
Added mcHF 0.7 bootloader install

### CODE REVIEW

**Comment by df8oe** [comment]
What's the problem - why is it shown to me as "conflicting"?

**Comment by db4ple** [comment]
There is a "conflict" in uhsdr_tool.py, I don't understand really why this is a conflict (it is an insertion of a comment). But in any case, you can merge it and keep the comment please. Unfortunately, I did not notice this problem before I committed the second part so I could not resolve it on my own easily.

**Comment by df8oe** [comment]
Yes. It is quite easy to solve - I thought you have an idea how it was born...

**Comment by df8oe** [comment]
Now I have seen! The PR was against branch auto-testing which does not exist here...

**Pull request merged**
