### PR TITLE
Virtual Keypads: band selection+direct frequency enter, modulation selection.

### PR DESCRIPTION
**Pull request by sp9bsl**
Band selection accessible by presing the most significant digits of frequency display, for 320x240 simplified keypad. Direct frequency enter works only for 480x320, also modulation selection is only for 480x320. Modified 480x320 layout to have modulation type and mode in one column with exact size. Modulation selection by pressing the type/mode items. Modulation type is displayed instead of old DIGITAL field (now SSB, CW, or digital modulation type).

### CODE REVIEW

**Comment by df8oe** [comment]
cool work. I like it very much :)

**Comment by sp9bsl** [comment]
Hi Andreas,
thanks, it needs testing. I'm on holidays and have only F4 rig here :)

**Comment by df8oe** [comment]
I can confirm it works on OVI40.

vy 73
Andreas

**Comment by K4LXY** [comment]
I downloaded and installed this morning's v46 (twice) but it shows v45 on the start-up screen.  I haven’t tried to figure out if it’s v46 without a name change but thought I’d let you know.
Tnx
73 Howard K4LXY


Howard Zehr
Photo galleries:  
www.howardzehr.com <http://www.howardzehr.com/>
https://www.facebook.com/HowardZehrPhoto

**Comment by df8oe** [comment]
Many thanks for the report. It was a broken link and is fixed now.

vy 73
Andreas

**Pull request merged**
