### PR TITLE
Improvements to 8x8 LCD font

### PR DESCRIPTION
**Pull request by martinling**
I have been playing with the CW decoder a bit lately (I can copy myself but not that quick yet!) and found myself getting quite annoyed by some of the oddities of the 8x8 font used in the message scroller. In particular, the `U` always looked too much like a `V` to me and some of the letter and number widths were quite uneven.

I don't know how the font data was originally created and converted into the array values included in the code, but since that seemed to be the only format it existed in, I wrote a Python script to display the font, extract it into an image file for editing, and then convert the image back to the necessary array values and put them in the source code. That's the first commit on this branch.

Then I made my proposed changes to the font, which are in the second commit. Before:

old-8x8

After:

new-8x8

The changes are:

- More rounded bottom on `U` to better distinguish from `V`
- Cleaner shapes to `V`, `W` and `M`.
- More consistent widths to other captials and numerals.
- Add serifs to `1` and `I` to better distinguish them.
- Add a slash through `0` to better distinguish from `O`.
- Clean up lowercase letters (particularly `f`, `g`, `p`, `q` and `y`) for more consistent height and style.

Obviously this is all somewhat a matter of taste so let me know what you think.

Changes tested on my mcHF 0.6. Screenshot with some of the changes visible below.
IMG_20190311_085014

### CODE REVIEW

**Comment by sp9bsl** [comment]
Hi,
why did you change the structure for 8 bit font (grayscale)? These fonts are used for frequency display. Definitelly out of your interest for this change...  This causes Travis warning.

**Comment by martinling** [comment]
Hi, not sure I follow you - I haven't made any changes to the grayscale fonts, only the 8x8 1bit font.

**Comment by sp9bsl** [comment]
you have added line 1828, and changed 1833. There is double init of field `maxCode` in these lines, and that's why Travis warns...

**Comment by martinling** [comment]
Ah, whoops, don't know how that happened. I've rebased without that chunk now.

**Comment by df8oe** [comment]
Hi Martin,

everyone who contributes to UHSR can be listed in the "Hall of Fame" - with callsign (if present) and/or name. If you want to be present there please tell me.

vy 73
Andreas

**Comment by martinling** [comment]
What an honour! Can it wait a little while - I have a UK intermediate callsign but I am am sitting the final test in a couple of weeks, so will have an M0 callsign for life after that, which would surely make more sense to include there.

**Comment by df8oe** [comment]
Of course it can wait. It's just an offer :) And we hope to get more contributions which improve UHSDR...

**Comment by martinling** [comment]
Hi @df8oe, my callsign M0LNG was allocated today if you want to add it to the credits.

**Comment by df8oe** [comment]
Congrats! It will be added at next releasing of binaries.

**Pull request merged**
