### PR TITLE
Lcd experimental

### PR DESCRIPTION
**Pull request by sp9bsl**
Added experimental waterfall in free space on LCD.

### CODE REVIEW

**Comment by df8oe** [comment]
This pull request has problems. You don't have rebased before creating pull request...
1) put  mchf-eclipse/.settings/org.eclipse.cdt.managedbuilder.core.prefs in your .gitignore
2) please rebase and commit the result

Of course it is possible to solve this via command line git - but for getting more familar with git I will not do so. Please ask again if you do need help.

**Comment by sp9bsl** [comment]
Andreas, i rebased and pushed it again, is it now okay?
image

**Comment by db4ple** [comment]
Hi Andreas,
I am not sure what the issue is here. Can you tell me how to see the merge conflicts GitHub talks about?

**Comment by df8oe** [comment]
No. It has conflicts... You see them at the bottom of your PR (or do only OI see them because it is my repo??)

Here the problems:

Conflicting files
mchf-eclipse/.settings/org.eclipse.cdt.managedbuilder.core.prefs
mchf-eclipse/drivers/ui/lcd/ui_lcd_hy28.c
mchf-eclipse/src/uhsdr_version.h

**Comment by db4ple** [comment]
Hi Andreas, I can see the conflicting files but have no idea how to see the conflicts
73
Danilo

**Comment by sp9bsl** [comment]
i did rebase just before first push, i had a conflict with version so i changed it and did rebase continue, after everything was ok i did push. Now i added to .gitignore file you asked and rebase it and push again.

**Comment by db4ple** [comment]
Hi Slawek, don't worry. We'll work that out. Just continue to work on your branch.

**Comment by db4ple** [comment]
@df8oe : It seems only someone with write access can actually see the conflicts. Funny thing. Found here:
https://stackoverflow.com/questions/32222402/is-there-a-way-to-see-merge-conflict-on-github-by-comparing-branches

73
Danilo

**Comment by df8oe** [comment]
That is quite curious. I will fix this manually on console and tell you what was going wrong.

**Comment by df8oe** [comment]
??? Version number in uhsdr_version.h differs, pin definitions in ui_lcd_hy28.c was corrupted and eclipse file was not present at my repo. I have not touched anything since last merge from Slawek... Please rebase now.

**Comment by sp9bsl** [comment]
I removed pin definitions from ui_lcd_hy28.c yestarday as we discussed it with Danilo. Now when i try to rebase i have:
image

is it ok?

**Comment by df8oe** [comment]
no. That's not ok. I see it too. No idea. I have fixed it manually. Hope now all is working.

**Comment by sp9bsl** [comment]
should i rebase now? I did something wrong but i have no idea what.

**Comment by df8oe** [comment]
Yes. Now everything is clear.

**Pull request merged**
